### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by brylie** [yooksi/cities-skylines-traffic-assets#4]
Please consider adding a license to this repository. That way, people know what rights you grant with regards to redistribution and modification of these models.

For what it's worth, I am researching open source game assets while planning an open source city building game project, and would like to use these assets.

**Comment by matshou** [comment]
Hey @brylie, I am sorry for not responding sooner. I honestly didn't see this until now. As per your request I have created a repository [license](https://github.com/yooksi/cities-skylines-assets/blob/master/LICENSE.md) that best reflects how I feel about sharing these assets.

Concerning your open source game project, I would be very happy to take a look and maybe lend you a hand with what I can if your project is something I find interesting. Let me know what you think :)

**Comment by brylie** [comment]
Thanks @yooksi! The city building is on the back burner, while keeping an eye to the Citybound and Kotcity projects. The main idea was to build a lo-fi, 3D city building game using Godot engine and publishing all assets on OpenGameArt/Godot Asset Library (where relevant). The idea was to integrate into larger game developer/designer communities.

**Comment by matshou** [comment]
@brylie That sounds great! So the community would be actively involved in the development process early on (possibly from alpha) and would basically build the game with the developers instead of building everything yourself and then allowing people to tack on mods and assets like in Cities Skylines?

I have some basic experience working with Godot, although that only extends to completing the in-depth tutorial and adding some custom animations and interesting new physics in code. The engine shows real promise and is not that hard to work with when you get your bearings.

By "back burner" you mean it's just an idea and has not been started already? If you ever do start the project (even opening a repo) be sure to let me know, I would be more then happy to jump on board such a project, if you are in need of some assistance at that time that is.

**Comment by brylie** [comment]
> By "back burner" you mean it's just an idea and has not been started already? If you ever do start the project (even opening a repo) be sure to let me know, I would be more then happy to jump on board such a project, if you are in need of some assistance at that time that is.

Yes, I haven't set up the repo. I will set one up ASAP, and commit an initial experiment. Hopefully, I will be able to import your game assets and place them on a simple 3D terrain.
